### PR TITLE
Main#VERSION: Fix typo

### PR DESCRIPTION
**Pull request by donjar**

### CODE REVIEW

**Comment by damithc** [comment]
Thank for the PR @donjar

**Comment by damithc** [comment]
@Zhiyuan-Amos shepherd this through when you have time. No hurry.

**Comment by Zhiyuan-Amos** [comment]
Thanks for your PR @donjar. ^^ Now for some finishing touches:

Your PR title is slightly long. How about something like `Main#VERSION: Fix typo`? It's more concise.

**Comment by Zhiyuan-Amos** [comment]
Hey Herbert, Zhi Yuan here (not sure if you do rmb me) ^^ 

Since this is a really small PR, I have updated the PR title to make it more concise. Also, in your original PR title, it's missing the class in which this `VERSION` string is located. 

Once again, thanks for your contribution!

**Comment by donjar** [comment]
Hey man - thanks for merging :) (sorry for being inactive, I was full whole
day) I'll try to follow the contributing rules next time!

**Pull request merged**
